
import { 
  BookOpen, 
  Search, 
  Scale, 
  Calculator, 
  Music, 
  Brain, 
  Users, 
  TestTube, 
  Cog, 
  Shovel, 
  Wrench, 
  Dna, 
  Factory, 
  Stethoscope, 
  Pill, 
  Atom, 
  Sprout, 
  Heart, 
  PawPrint, 
  FileText, 
  Church, 
  Feather, 
  Building, 
  GraduationCap, 
  Chalkboard, 
  Coffee, 
  Printer, 
  Trophy, 
  Monitor,
  Sun
} from 'lucide-react';

export const getIconForBuilding = (type: string) => {
  const iconMap: { [key: string]: any } = {
    'lecture-room': BookOpen,
    'sherlock-holmes': Search,
    'judge': Scale,
    'mathematics': Calculator,
    'concert': Music,
    'brain': Brain,
    'conference': Users,
    'test-tubes': TestTube,
    'engineering': Cog,
    'earth-science': Shovel,
    'dna': Dna,
    'materials': Wrench,
    'medical': Stethoscope,
    'pharmacy': Pill,
    'physics': Atom,
    'plant': Sprout,
    'psychology': Heart,
    'veterinary': PawPrint,
    'animals': PawPrint,
    'office': FileText,
    'religious': Church,
    'shakespeare': Feather,
    'law': Scale,
    'music': Music,
    'town-hall': Building,
    'factory': Factory,
    'teacher': GraduationCap,
    'classroom': Chalkboard,
    'restaurant': Coffee,
    'printing': Printer,
    'sports': Trophy,
    'computer': Monitor,
    'day-off': Sun
  };

  return iconMap[type] || BookOpen;
};
